"""
AI-Driven Configuration Generator
---------------------------------
This module automates the discovery and classification of UI elements.
It combines Playwright's DOM traversal capabilities with Gemini's 
semantic reasoning to generate structured navigation configurations.
"""

import os
import json
from playwright.async_api import async_playwright
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage
from dotenv import load_dotenv

# Initialize environment variables for API and Model access
load_dotenv()

class ConfigGenerator:
    """
    Orchestrates the scanning of web pages to produce AI-enriched 
    JSON configurations for the Agentic-QA-Explorer.
    """

    def __init__(self):
        """
        Initializes the generator with the specified Gemini model 
        and authentication credentials.
        """
        # Ensure model consistency across the framework
        self.model_name = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")

        # Configure the LangChain wrapper for Google Generative AI
        self.llm = ChatGoogleGenerativeAI(
            model=self.model_name,
            google_api_key=os.getenv("GOOGLE_API_KEY"),
            temperature=0,
            convert_system_message_to_human=True
        )

    async def get_interactive_elements(self, page):
        """
        Scans the current page session for visible and interactive DOM nodes.

        Args:
            page (playwright.async_api.Page): The active browser page instance.

        Returns:
            list: A collection of dictionaries containing element metadata (tag, ID, visibility).
        """
        # Target standard interactive HTML elements and ARIA roles
        selector = "button, input, a, select, [role='button']"
        elements = await page.query_selector_all(selector)
        
        extracted_data = []
        for el in elements:
            # Evaluate element properties within the browser context
            data = await el.evaluate("""(node) => {
                return {
                    tag: node.tagName,
                    id: node.id,
                    type: node.getAttribute('type') || '',
                    text: node.innerText.trim() || 
                          node.getAttribute('placeholder') || 
                          node.getAttribute('aria-label') || '',
                    isVisible: node.offsetWidth > 0 && node.offsetHeight > 0
                }
            }""")
            
            # Filter for elements that are actionable (have an ID and are visible)
            if data['id'] and data['isVisible']:
                extracted_data.append(data)
        
        return extracted_data

    async def generate_enriched_config(self, url, page_name, instructions):
        """
        Navigates to a URL, extracts the DOM state, and uses the LLM 
        to classify elements into a structured schema.

        Args:
            url (str): The target web address to scan.
            page_name (str): The logical name to assign to this page state.
            instructions (str): The prompt engineering guide for the LLM.

        Returns:
            dict: The JSON-formatted configuration data generated by the LLM.
        """
        async with async_playwright() as p:
            # Launch a headless instance for background processing
            browser = await p.chromium.launch(headless=True)
            page = await browser.new_page()
            
            print(f"[SCANNING]: Initializing DOM traversal at {url}...")
            await page.goto(url)
            await page.wait_for_load_state("networkidle")
            
            # Extract raw technical metadata from the page
            elements = await self.get_interactive_elements(page)
            
            # Construct a multimodal-ready prompt combining instructions and raw data
            prompt_text = (
                f"{instructions}\n\n"
                f"PAGE NAME: {page_name}\n"
                f"DOM ELEMENTS: {json.dumps(elements)}"
            )

            print(f"[REASONING]: Gemini analyzing {len(elements)} discovered elements...")
            
            # Invoke the LLM to perform semantic mapping/classification
            response = await self.llm.ainvoke([HumanMessage(content=prompt_text)])
            
            # Clean and sanitize the LLM response (strip Markdown formatting)
            clean_text = response.content.replace("```json", "").replace("```", "").strip()
            
            try:
                # Deserialize the cleaned string into a structured dictionary
                enriched_data = json.loads(clean_text)
                await browser.close()
                return enriched_data
            except Exception as e:
                print(f"[ERROR]: JSON transformation failed. Source: {e}")
                return None
            finally:
                await browser.close()